// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXpfsvWK60DrcJNj5CdS8eG5cf9Zapj4s',
    appId: '1:708085868882:web:9457db474c23726ce4728b',
    messagingSenderId: '708085868882',
    projectId: 'kopma-uin-suka-db2c7',
    authDomain: 'kopma-uin-suka-db2c7.firebaseapp.com',
    storageBucket: 'kopma-uin-suka-db2c7.appspot.com',
    measurementId: 'G-T5KJ4WPX58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwLQvIVPMQRjEX-mI_vSE7r7i_pkRyZes',
    appId: '1:708085868882:android:8cb8c00066f5714ee4728b',
    messagingSenderId: '708085868882',
    projectId: 'kopma-uin-suka-db2c7',
    storageBucket: 'kopma-uin-suka-db2c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbB2cR-0zKUuOmMApvBBpNYMPURc25OPc',
    appId: '1:708085868882:ios:dd7bde61b58af22fe4728b',
    messagingSenderId: '708085868882',
    projectId: 'kopma-uin-suka-db2c7',
    storageBucket: 'kopma-uin-suka-db2c7.appspot.com',
    iosBundleId: 'com.example.kopma',
  );
}

const iOSClientId = 'your-client-id.apps.googleusercontent.com';
const webClientId = '708085868882-sc6otf08s5e67vetbfiugkvkfba3u0os.apps.googleusercontent.com';


String get googleClientId {
  return switch (defaultTargetPlatform) {
    TargetPlatform.iOS || TargetPlatform.macOS => iOSClientId,
    _ => webClientId,
  };
}
